language: python

python:
    - "3.6"
    
install:
    pip install -r requirements.txt
    
script:
    - python -m unittest -v unittests/gateway_test/*.py
    - python -m unittest -v unittests/movie_tests/*.py
    - python -m unittest -v unittests/seance_tests/*.py
    - python -m unittest -v unittests/ticket_tests/*.py
    - python -m unittest -v unittests/user_tests/*.py